############# English navigation ##############

# main menu
[[main]]
name = "Hem"
url = "/"
weight = 1

[[main]]
name = "Om oss"
url = "about/"
weight = 2

[[main]]
name = "Projekt"
url = "elements/"
weight = 3

[[main]]
weight = 4
name = "Kontakta oss"
url = "pages/"


# footer menu
[[footer]]
name = "Om oss"
url = "about/"
weight = 1

[[footer]]
name = "Kontakta oss"
url = "pages/"
weight = 2

[[footer]]
name = "Projekt"
url = "elements/"
weight = 3
